spring.application.name=LU Librisync

spring.datasource.url=${LU_LIBRISYNC_DB_URL:jdbc:mysql://127.0.0.1:3306/lu_librisync?useSSL=false&serverTimezone=Asia/Manila&allowPublicKeyRetrieval=true}
spring.datasource.username=${LU_LIBRISYNC_DB_USERNAME:root}
spring.datasource.password=${LU_LIBRISYNC_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

server.error.whitelabel.enabled=false
server.servlet.session.timeout=30m

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
